### ISSUE TITLE
[PATCH] fix some spelling mistakes in the POD

### ISSUE THREAD

**Issue by gregoa** [maros/MooseX-App#39]
In Debian we are currently applying the following patch to
MooseX-App.
We thought you might be interested in it too.

    Description: fix some spelling mistakes in the POD
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-04-03
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libmoosex-app-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by maros** [comment]
Applied. Thank you for your contribution

**Comment by gregoa** [comment]
On Sat, 14 May 2016 09:05:46 -0700, Maroš Kollár wrote:

> Applied. Thank you for your contribution

Great, thanks!

Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Davy Graham: Stan's Guitar
