### ISSUE TITLE
Ability to turn off boolean negation added in 1.36

### ISSUE THREAD

**Issue by ah19** [maros/MooseX-App#45]
We have a lot of boolean options in our codebase like '--no-db' that after upgrading to 1.36 are now broken, as when --no-db is specified on the command line it tries to update the --db option, which doesn't exist, so our code no longer works.

I would rather be able to say `if ( $self->no_db )` as it is more readable the way we use it (we never check if it is false). Would it be possible to add an app setting like app_permute? Or a check to see if the no_ option exists and use it instead, so it is backwards compatible?

**Comment by maros** [comment]
Please checkout the lastest master HEAD. Does this fix the reported issues?
I have added an explicit cmd_negate option that lets you set option names for negating boolean options/flags.

**Comment by maros** [comment]
Fixed in 1.37
