### ISSUE TITLE
pod2man error

### ISSUE THREAD

**Issue by angelabad** [maros/MooseX-App#46]
Hi, packaging for Debian we found this pod2man error:

@@ -463,7 +463,7 @@
 
 Returns a list of all possible option names.
 
-=head cmd_name_list
+=head2 cmd_name_list
 
  my @names = $attribute->cmd_name_list();
 
Cheers,

**Comment by maros** [comment]
Thank you for the bug report. The isssue was fixed with 015bbad46aecde1f722c38bd4b800441004c35f2
