### ISSUE TITLE
How to specify ~/.myapprc as default config file with MooseX::App::Plugin::Config?

### ISSUE THREAD

**Issue by pmorch** [maros/MooseX-App#48]
It is a common idiom for `myapp` to have a default config file in `~/.myapprc` without requiring the user to specify `--config ~/.myapprc` for every invocation.

I've been trying this for _hours_ and can't get it to work with `MooseX::App::Plugin::Config`. I don't think it is possible, but would love to be proven wrong.

The only thing I've found to work is in my tiny launcher script to do:

    my $config = "$ENV{HOME}/.myapprc";
    if (-r $config && ! grep /^--config$/, @ARGV) {
        push @ARGV, '--config', $config;
    }

But that has a very nasty smell.

I've tried a [standard way](http://stackoverflow.com/a/15328736/345716) to override defaults set in Moose roles:

    has '+config' => (
        default => File::Spec->catfile($ENV{HOME}, '.myapprc')
    );

When I do that, I can get `$app->config` to have the right value, but `$app->_config_data` is still empty.

Then I tried to give `config` and `_config_data` as parameters to new as in:

    my $app = MyApp ->new_with_command(
        config => $config_file,
        _config_data => $config_data
    );

And that resulted in both options set, but `_config_data` doesn't serve as default values to the other options, and then it doesn't really matter.

The reason seems to be that `MooseX::App::Meta::Role::Class::Base`'s sub `command_parse_options ` iterates over `$parsed_argv->available('option')` and only then sets up default values for the other options. So if there is no `--config` option in `@ARGV` itself then the config attribute is ignored you can't set up a default config file. :-(  I must admit I didn't understand it fully but my `Moose` meta-foo is seriously lacking, and `Data::Dumper` is useless with all the noise from `Moose`.

Any idea how one could make it possible without having to modify `@ARGV` before calling `MooseX::App`?

**Comment by pmorch** [comment]
Sorry! That is what [MooseX::App::Plugin::ConfigHome - Config files in users home directory](https://metacpan.org/pod/MooseX::App::Plugin::ConfigHome) is for! I didn't find it until just now.

Feel free to close the issue.

**Comment by maros** [comment]
Please have a look at the ConfigHome plugin. This does exactly(?) what you are trying to achieve here. The config attribute is a little bit special, since it has to be evaluated BEFORE all other attributes - during the 'proto' processing stage.
