### ISSUE TITLE
Dependency on List::Util v1.44

### ISSUE THREAD

**Issue by jrmash** [maros/MooseX-App#49]
It seems that MX::App may depend on List::Util v1.44 (when the 'uniq' function was added), but does not explicitly declare it so:

>    Failed test 'use MooseX::App;'
>    at t/00_load.t line 7.
>      Tried to use 'MooseX::App'.
>      Error:  "uniq" is not exported by the List::Util module

I ran into that error on a machine that had List::Util v1.38 installed.

**Comment by maros** [comment]
Thank you for reporting this error. Will fix this in the next release

**Comment by maros** [comment]
Fixed in 1.38
