### ISSUE TITLE
Can't locate Config/Any.pm in @INC

### ISSUE THREAD

**Issue by eserte** [maros/MooseX-App#67]
It seems that there's a missing dependency or a missing skip in the test suite of 1.42: http://matrix.cpantesters.org/?dist=MooseX-App+1.42

A sample fail report: http://www.cpantesters.org/cpan/report/1fafb704-00a5-11ec-bc66-57723b537541

**Comment by maros** [comment]
Now always required, and not only feature depentant

**Comment by maros** [comment]
Released on cpan as 1.43
